nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5174']  # Remplace par l'URL de ton frontend
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        expose_headers: ['Link']
